cloudscale.dispatch=sqs
cloudscale.sqs.queue-url=${CLOUDSCALE_SQS_QUEUE_URL:}
cloudscale.sqs.region=${AWS_REGION:}
cloudscale.api.enabled=false
cloudscale.worker.enabled=true
spring.main.web-application-type=none
